# Generated by Django 6.0.3 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_feedback_answer_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
